### ISSUE TITLE
2xT4

### ISSUE THREAD

**Issue by C00reNUT** [dropreg/efficient_alpaca#1]
Hello,

just a quick question - would it be possible to run this on two T4GPUs with 2x16GB VRAM?

**Comment by dropreg** [comment]
Hi，

Thanks for your attention to our work.

Our project supports 2 * 24G GPUs for efficient tuning (LoRA) to reproduce Stanford Alpaca, and 2 * 16G GPUs for inference (or deployment).

Clearly,  If you want to use 16G GPUs for training, you may need 4 * 16G GPUs，and run `python alpaca_lora/scripts/utils/process_llama_megatron_ckpt.py --llama-model-dir $llama_dir --llama-model-file $llama_file --parallel-size 4` to obtain LLaMA model fragments.

Hope above helps!
